runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico 

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: filmi.application
